// tools/embed-guides.mjs — bake the /Guides HTML files into gym-tracker.html as inert
// <template> blocks, so the app ships as a single self-contained file (no /Guides needed
// to distribute). Idempotent: re-run whenever a guide changes. The in-app reader
// (openGuide / buildGuideTheme in gym-tracker.html) renders each guide in an iframe and
// themes it to the app's live palette + font at open time.
//
//   node tools/embed-guides.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const APP = join(root, 'gym-tracker.html');
const GUIDES = [
  { id: 'bouldering', title: 'Bouldering — Field Guide', file: 'Guides/bouldering-guide.html' },
  { id: 'coc', title: 'Captains of Crush — Grip Masterclass', file: 'Guides/coc-masterclass.html' },
  { id: 'endurance', title: 'Endurance Reference', file: 'Guides/endurance-reference.html' },
];

const templates = GUIDES.map((g) => {
  let raw = readFileSync(join(root, g.file), 'utf8');
  raw = raw.replace(/<link\b[^>]*>/gi, ''); // drop external font/CDN <link>s — stays offline-friendly (reader overrides the font anyway)
  if (/<\/template>/i.test(raw)) throw new Error(g.file + ' contains </template> — cannot embed safely');
  return `<template id="guide-${g.id}" data-title="${g.title}">\n${raw}\n</template>`;
}).join('\n');

const block = '<!-- GUIDES:START (generated by tools/embed-guides.mjs from /Guides — do not edit by hand) -->\n'
  + templates + '\n<!-- GUIDES:END -->';

let html = readFileSync(APP, 'utf8');
const re = /<!-- GUIDES:START[\s\S]*?<!-- GUIDES:END -->/;
if (re.test(html)) html = html.replace(re, block);
else if (html.includes('</body>')) html = html.replace('</body>', block + '\n</body>');
else throw new Error('gym-tracker.html has no </body> to insert before');
writeFileSync(APP, html);
console.log(`embedded ${GUIDES.length} guides (${(block.length / 1024).toFixed(0)} KB) into gym-tracker.html`);
